wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
num_batches:
  desc: null
  value: 2000
VOCAB_SIZE:
  desc: null
  value: 12
threshold:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 512
seq_length:
  desc: null
  value: 10
start_token_val:
  desc: null
  value: 0
end_token_val:
  desc: null
  value: 11
step_size:
  desc: null
  value: 250
gamma:
  desc: null
  value: 0.85
num_encoder_decoder_layers:
  desc: null
  value: 6
num_heads:
  desc: null
  value: 8
d_model:
  desc: null
  value: 64
d_ff:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.1
print_result_at:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711436903.1416
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 5
